---

- hosts: all
  become: yes
  roles:
    - { role: common, tags: ['common'] }

- hosts: webservers
  become: yes
  roles:
    - { role: apache, tags: ['apache'] }

- hosts: loadbalancers
  become: yes
  roles:
    - { role: haproxy, tags: ['haproxy'] }
